In [27]:
import numpy as np
import pandas as pd

In [28]:
df=pd.read_csv("ev_vehicle_dataset_messy.csv")

In [29]:
df.head()

,Vehicle_ID,Car_Model,Battery_Type,Battery_Capacity_kWh,Vehicle_Age_Months,Total_Charging_Cycles,Avg_Temperature_C,Fast_Charge_Ratio,Avg_Discharge_Rate_C,Driving_Style,Internal_Resistance_Ohm,SoH_Percent,Battery_Status
0,1fb46ae8,Tesla Model 3,NMC,75.0,106.0,1958.0,42.30,0.714,2.17,Aggressive,0.075,38.79,NaN
1,b7ef35aa,Tesla Model 3,NaN,75.0,29.0,401.0,18.00,0.620,1.34,Aggressive,NaN,94.03,Healthy
2,76cb49e0,Ford Mustang Mach-E,NMC,88.0,71.0,941.0,18.40,0.780,1.48,NaN,0.010,80.40,Healthy
3,456a7aef,Ford Mustang Mach-E,NMC,88.0,107.0,1573.0,40.33,0.920,2.36,Moderate,NaN,69.96,Unhealthy
4,bd758049,Tesla Model 3,NMC,75.0,58.0,239.0,30.30,0.890,1.48,NaN,NaN,90.80,Healthy

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10050 entries, 0 to 10049
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Vehicle_ID               9158 non-null   object
 1   Car_Model                9306 non-null   object
 2   Battery_Type             9271 non-null   object
 3   Battery_Capacity_kWh     9262 non-null   float64
 4   Vehicle_Age_Months       9274 non-null   float64
 5   Total_Charging_Cycles    9311 non-null   float64
 6   Avg_Temperature_C        9225 non-null   float64
 7   Fast_Charge_Ratio        9248 non-null   float64
 8   Avg_Discharge_Rate_C     9252 non-null   float64
 9   Driving_Style            9290 non-null   object
 10  Internal_Resistance_Ohm  9251 non-null   float64
 11  SoH_Percent              9258 non-null   float64
 12  Battery_Status           9255 non-null   object
dtypes: float64(8), object(5)
memory usage: 1020.8+ KB

In [31]:
df.describe()

,Battery_Capacity_kWh,Vehicle_Age_Months,Total_Charging_Cycles,Avg_Temperature_C,Fast_Charge_Ratio,Avg_Discharge_Rate_C,Internal_Resistance_Ohm,SoH_Percent
count,9262.000000,9274.000000,9311.000000,9225.000000,9248.000000,9252.000000,9251.000000,9258.000000
mean,64.603066,64.770649,829.348405,32.084246,0.641556,2.004774,0.050159,73.937742
std,20.946405,31.614249,562.159788,10.835273,0.286557,0.808378,0.031547,19.941988
min,26.000000,1.000000,4.000000,-12.900000,0.000000,0.500000,0.010000,35.010000
25%,60.000000,40.000000,336.000000,23.500000,0.420000,1.340000,0.024000,55.125000
50%,72.600000,69.000000,798.000000,32.900000,0.742000,2.090000,0.039000,82.940000
75%,75.000000,89.000000,1265.000000,41.100000,0.870000,2.560000,0.075000,90.547500
max,88.000000,119.000000,1999.000000,53.600000,1.000000,3.500000,0.120000,98.000000

In [32]:

df.isnull().sum()

Vehicle_ID                 892
Car_Model                  744
Battery_Type               779
Battery_Capacity_kWh       788
Vehicle_Age_Months         776
Total_Charging_Cycles      739
Avg_Temperature_C          825
Fast_Charge_Ratio          802
Avg_Discharge_Rate_C       798
Driving_Style              760
Internal_Resistance_Ohm    799
SoH_Percent                792
Battery_Status             795
dtype: int64

In [33]:
df.columns

Index(['Vehicle_ID', 'Car_Model', 'Battery_Type', 'Battery_Capacity_kWh',
       'Vehicle_Age_Months', 'Total_Charging_Cycles', 'Avg_Temperature_C',
       'Fast_Charge_Ratio', 'Avg_Discharge_Rate_C', 'Driving_Style',
       'Internal_Resistance_Ohm', 'SoH_Percent', 'Battery_Status'],
      dtype='object')

In [34]:
df = df.drop(columns=["Vehicle_ID"])

In [35]:
df.columns

Index(['Car_Model', 'Battery_Type', 'Battery_Capacity_kWh',
       'Vehicle_Age_Months', 'Total_Charging_Cycles', 'Avg_Temperature_C',
       'Fast_Charge_Ratio', 'Avg_Discharge_Rate_C', 'Driving_Style',
       'Internal_Resistance_Ohm', 'SoH_Percent', 'Battery_Status'],
      dtype='object')

In [36]:
df=df.dropna(subset=['Battery_Status'])
df["Battery_Status"].head()

1      Healthy
2      Healthy
3    Unhealthy
4      Healthy
5      Healthy
Name: Battery_Status, dtype: object

In [37]:
df = df.dropna(subset=["SoH_Percent"])
df["SoH_Percent"].head()

1    94.03
2    80.40
3    69.96
4    90.80
5    92.52
Name: SoH_Percent, dtype: float64

null values in Car_Model,Driving_Style is filled with mode

In [38]:
print(df["Car_Model"].mode())
df['Car_Model']=df['Car_Model'].fillna("BYD Atto 3")
df["Car_Model"].head(10)

0    BYD Atto 3
Name: Car_Model, dtype: object

1           Tesla Model 3
2     Ford Mustang Mach-E
3     Ford Mustang Mach-E
4           Tesla Model 3
5         Hyundai Ioniq 5
6         Hyundai Ioniq 5
7         Hyundai Ioniq 5
8     Ford Mustang Mach-E
9           Wuling Air EV
10          Tesla Model 3
Name: Car_Model, dtype: object

In [39]:
print(df["Driving_Style"].mode())
df["Driving_Style"].str.lower()
df["Driving_Style"].str.strip()
df["Driving_Style"]=df["Driving_Style"].fillna("Moderate")
df["Driving_Style"].head()

0    Moderate
Name: Driving_Style, dtype: object

1    Aggressive
2      Moderate
3      Moderate
4      Moderate
5      Moderate
Name: Driving_Style, dtype: object

In [40]:
df["Car_Model"]=df["Car_Model"].str.lower()
df["Car_Model"]=df["Car_Model"].str.strip()

In [41]:
df["Car_Model"].head(100
                     )

1            tesla model 3
2      ford mustang mach-e
3      ford mustang mach-e
4            tesla model 3
5          hyundai ioniq 5
              ...
115             byd atto 3
116             byd atto 3
117    ford mustang mach-e
118          tesla model 3
119          wuling air ev
Name: Car_Model, Length: 100, dtype: object

In [42]:
print(df["Car_Model"].unique())

df.loc[df["Battery_Type"].isnull()&(df["Car_Model"]=='wuling air ev'),"Battery_Type"]="LFP"
df.loc[df["Battery_Type"].isnull()&(df["Car_Model"]=='tesla model 3'),"Battery_Type"]="NMC"
df.loc[df["Battery_Type"].isnull()&(df["Car_Model"]=='ford mustang mach-e'),"Battery_Type"]="NMC"
df.loc[df["Battery_Type"].isnull()&(df["Car_Model"]=='hyundai ioniq 5'),"Battery_Type"]="NMC"
df.loc[df["Battery_Type"].isnull()&(df["Car_Model"]=='byd atto 3'),"Battery_Type"]="LFP"

['tesla model 3' 'ford mustang mach-e' 'hyundai ioniq 5' 'wuling air ev'
 'byd atto 3']

In [43]:
df.isnull().sum()

Car_Model                    0
Battery_Type                 0
Battery_Capacity_kWh       618
Vehicle_Age_Months         631
Total_Charging_Cycles      604
Avg_Temperature_C          675
Fast_Charge_Ratio          633
Avg_Discharge_Rate_C       646
Driving_Style                0
Internal_Resistance_Ohm    646
SoH_Percent                  0
Battery_Status               0
dtype: int64

In [44]:
df["Battery_Type"].head(10)

1       NMC
2       NMC
3       NMC
4       NMC
5       NMC
6       NMC
7       NMC
8      NMC
9       LFP
10      NMC
Name: Battery_Type, dtype: object

null values in Battery_Capacity_kWh,Total_Charging_Cycles,Fast_Charge_Ratio,Internal_Resistance_Ohm is filled with median

In [45]:
print(df["Battery_Capacity_kWh"].median())
df["Battery_Capacity_kWh"]=df["Battery_Capacity_kWh"].fillna(72)
df["Battery_Capacity_kWh"]=df["Battery_Capacity_kWh"].astype(int)
df["Battery_Capacity_kWh"].head(7)

72.6

1    75
2    88
3    88
4    75
5    72
6    72
7    72
Name: Battery_Capacity_kWh, dtype: int64

In [46]:
print(df["Total_Charging_Cycles"].median())
df["Total_Charging_Cycles"]=df["Total_Charging_Cycles"].fillna(df["Total_Charging_Cycles"].median())
df["Total_Charging_Cycles"].head(7)

798.0

1     401.0
2     941.0
3    1573.0
4     239.0
5     798.0
6     734.0
7     121.0
Name: Total_Charging_Cycles, dtype: float64

In [47]:
print(df["Fast_Charge_Ratio"].median())
df["Fast_Charge_Ratio"]=df["Fast_Charge_Ratio"].fillna(df["Fast_Charge_Ratio"].median())
df["Fast_Charge_Ratio"].head(200)

0.741

1      0.620
2      0.780
3      0.920
4      0.890
5      0.350
       ...
234    0.770
236    0.920
237    0.741
238    0.610
239    0.787
Name: Fast_Charge_Ratio, Length: 200, dtype: float64

In [48]:
print(df["Internal_Resistance_Ohm"].median())
df["Internal_Resistance_Ohm"]=df["Internal_Resistance_Ohm"].fillna(df["Internal_Resistance_Ohm"].median())
df["Internal_Resistance_Ohm"].head(10)

0.039

1     0.039
2     0.010
3     0.039
4     0.039
5     0.024
6     0.022
7     0.025
8     0.062
9     0.032
10    0.118
Name: Internal_Resistance_Ohm, dtype: float64

null values in Vehicle_Age_Months,Avg_Temperature_C,Avg_Discharge_Rate_C is filled with mean

In [49]:
print(df["Vehicle_Age_Months"].mean())
df["Vehicle_Age_Months"]=df["Vehicle_Age_Months"].fillna(65)
df["Vehicle_Age_Months"].head(2100)

64.89965921999243

1        29.0
2        71.0
3       107.0
4        58.0
5        27.0
        ...
2453     76.0
2454      7.0
2455     83.0
2456     70.0
2457     60.0
Name: Vehicle_Age_Months, Length: 2100, dtype: float64

In [50]:
print(df["Avg_Temperature_C"].mean())
df["Avg_Temperature_C"]=df["Avg_Temperature_C"].fillna(32.09)
df["Avg_Temperature_C"].head(10)

32.05482929305749

1     18.00
2     18.40
3     40.33
4     30.30
5     20.00
6      3.20
7     27.40
8     47.56
9     32.09
10    41.90
Name: Avg_Temperature_C, dtype: float64

In [51]:
df["Battery_Status"]=df["Battery_Status"].str.lower()
df["Driving_Style"]=df["Driving_Style"].str.lower()

In [53]:
print(df["Avg_Discharge_Rate_C"].mean())
df["Avg_Discharge_Rate_C"]=df["Avg_Discharge_Rate_C"].fillna(2.00)
df["Avg_Discharge_Rate_C"].head(10)

2.0057844283376203

1     1.34
2     1.48
3     2.36
4     1.48
5     2.50
6     0.65
7     1.41
8     2.93
9     1.50
10    2.44
Name: Avg_Discharge_Rate_C, dtype: float64

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8554 entries, 1 to 9998
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Car_Model                8554 non-null   object
 1   Battery_Type             8554 non-null   object
 2   Battery_Capacity_kWh     8554 non-null   int64
 3   Vehicle_Age_Months       8554 non-null   float64
 4   Total_Charging_Cycles    8554 non-null   float64
 5   Avg_Temperature_C        8554 non-null   float64
 6   Fast_Charge_Ratio        8554 non-null   float64
 7   Avg_Discharge_Rate_C     8554 non-null   float64
 8   Driving_Style            8554 non-null   object
 9   Internal_Resistance_Ohm  8554 non-null   float64
 10  SoH_Percent              8554 non-null   float64
 11  Battery_Status           8554 non-null   object
dtypes: float64(7), int64(1), object(4)
memory usage: 868.8+ KB

In [55]:
df.isnull().sum()

Car_Model                  0
Battery_Type               0
Battery_Capacity_kWh       0
Vehicle_Age_Months         0
Total_Charging_Cycles      0
Avg_Temperature_C          0
Fast_Charge_Ratio          0
Avg_Discharge_Rate_C       0
Driving_Style              0
Internal_Resistance_Ohm    0
SoH_Percent                0
Battery_Status             0
dtype: int64

In [56]:
df.shape
df['Car_Model'].unique()

array(['tesla model 3', 'ford mustang mach-e', 'hyundai ioniq 5',
       'wuling air ev', 'byd atto 3'], dtype=object)

In [63]:
df.to_csv("ev_vehicle_battery_preprocessed_dataset.csv",index=False)

In [58]:
df["Battery_Type"]=df["Battery_Type"].str.lower()
df['Battery_Type']=df['Battery_Type'].str.strip()

In [59]:
#df["Driving_Style"].unique()
df["Driving_Style"]=df["Driving_Style"].str.lower()
df["Driving_Style"]=df["Driving_Style"].str.strip()

In [60]:
df["Driving_Style"].unique()

array(['aggressive', 'moderate', 'conservative'], dtype=object)

In [61]:
df["Battery_Status"]=df["Battery_Status"].str.lower()
df["Battery_Status"]=df["Battery_Status"].str.strip()